//go:build go1.22

// Package http_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package http_server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for K0sPostActionParamsAction.
const (
	K0sPostActionParamsActionStart K0sPostActionParamsAction = "start"
	K0sPostActionParamsActionStop  K0sPostActionParamsAction = "stop"
)

// Defines values for LibvirtPostDomainActionParamsAction.
const (
	LibvirtPostDomainActionParamsActionReboot   LibvirtPostDomainActionParamsAction = "reboot"
	LibvirtPostDomainActionParamsActionShutdown LibvirtPostDomainActionParamsAction = "shutdown"
	LibvirtPostDomainActionParamsActionStart    LibvirtPostDomainActionParamsAction = "start"
)

// Defines values for PkiSshSignaturesGetParamsType.
const (
	PkiSshSignaturesGetParamsTypeHost PkiSshSignaturesGetParamsType = "host"
	PkiSshSignaturesGetParamsTypeUser PkiSshSignaturesGetParamsType = "user"
)

// Defines values for PkiSshSignaturesPostParamsType.
const (
	PkiSshSignaturesPostParamsTypeHost PkiSshSignaturesPostParamsType = "host"
	PkiSshSignaturesPostParamsTypeUser PkiSshSignaturesPostParamsType = "user"
)

// Defines values for ServicesUnitStatusPutParamsAction.
const (
	ServicesUnitStatusPutParamsActionReboot   ServicesUnitStatusPutParamsAction = "reboot"
	ServicesUnitStatusPutParamsActionShutdown ServicesUnitStatusPutParamsAction = "shutdown"
	ServicesUnitStatusPutParamsActionStart    ServicesUnitStatusPutParamsAction = "start"
)

// Defines values for SystemPowerConditionalRebootPostStatusParamsAction.
const (
	Pause   SystemPowerConditionalRebootPostStatusParamsAction = "pause"
	Unpause SystemPowerConditionalRebootPostStatusParamsAction = "unpause"
)

// Defines values for SystemPowerPostActionParamsAction.
const (
	SystemPowerPostActionParamsActionReboot   SystemPowerPostActionParamsAction = "reboot"
	SystemPowerPostActionParamsActionShutdown SystemPowerPostActionParamsAction = "shutdown"
)

// DnfPackageInfo Info about a single package
type DnfPackageInfo struct {
	// Name Name of the package
	Name *string `json:"name,omitempty"`

	// Repo Repository from which the package was installed
	Repo *string `json:"repo,omitempty"`

	// Version Version of the package
	Version *string `json:"version,omitempty"`
}

// Issuer Information about the issuer of the certificate.
type Issuer struct {
	// CommonName The common name of the issuer.
	CommonName string `json:"commonName"`

	// SerialNumber The serial number of the issuer.
	SerialNumber string `json:"serialNumber"`
}

// Logs Raw log data
type Logs struct {
	Logs []string `json:"logs,omitempty"`
}

// PackagesInstalledResponse List of all the installed packages on a system
type PackagesInstalledResponse struct {
	// Packages List of installed packages
	Packages *[]DnfPackageInfo `json:"packages,omitempty"`
}

// PackagesUpdatesResponse Returns whether system updates are available
type PackagesUpdatesResponse struct {
	// UpdatablePackages List of packages that can be updated
	UpdatablePackages *[]DnfPackageInfo `json:"updatable_packages,omitempty"`

	// UpdatesAvailable Indicates if there are updates available
	UpdatesAvailable *bool `json:"updates_available,omitempty"`
}

// PkiSshConfig Holds information about the certificate and which action was taken
type PkiSshConfig struct {
	CertType *string `json:"certType,omitempty"`

	// CertInfo General information about a SSH certificate
	CertInfo *SshSignerCertificateInfo `json:"cert_info,omitempty"`

	// CertificateFile The file to write the signed cert to
	CertificateFile *string   `json:"certificateFile,omitempty"`
	Principals      *[]string `json:"principals,omitempty"`

	// PublicKeyFile The file to read the SSH public key from
	PublicKeyFile *string `json:"publicKeyFile,omitempty"`

	// Role Name of the vault role
	Role *string `json:"role,omitempty"`

	// Ttl The desired TTL of the signature
	Ttl *string `json:"ttl,omitempty"`
}

// Problem A generic HTTP problem
type Problem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code
	Status *int `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type
	Title *string `json:"title,omitempty"`

	// Type A URI reference that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// SecretReplicationItems List of all configured sync items
type SecretReplicationItems struct {
	// Data The sync items
	Data []SecretSyncerSyncItem `json:"data,omitempty"`
}

// SecretSyncerSyncItem Configuration for a single secret sync request
type SecretSyncerSyncItem struct {
	// DestUri destination path where the read secret should be writen to
	DestUri string `json:"dest_uri,omitempty"`

	// Formatter name of the formatter
	Formatter string `json:"formatter,omitempty"`

	// SecretPath path of the secret to read and sync to the local filesystem
	SecretPath string `json:"secret_path,omitempty"`
}

// ServiceLogsData Logs data for a service
type ServiceLogsData struct {
	// Data Raw log data
	Data  *Logs   `json:"data,omitempty"`
	Error *string `json:"error"`
}

// SshSignerCertificateInfo General information about a SSH certificate
type SshSignerCertificateInfo struct {
	CertificateFile *string    `json:"certificate_file,omitempty"`
	CertificateType *string    `json:"certificate_type,omitempty"`
	Percentage      *float32   `json:"percentage,omitempty"`
	PublicKeyFile   *string    `json:"public_key_file,omitempty"`
	Serial          *int64     `json:"serial,omitempty"`
	ValidAfter      *time.Time `json:"valid_after,omitempty"`
	ValidBefore     *time.Time `json:"valid_before,omitempty"`
}

// X509CertInfo Information about an X509 certificate.
type X509CertInfo struct {
	// EmailAddresses A list of email addresses associated with the certificate.
	EmailAddresses *[]openapi_types.Email `json:"emailAddresses,omitempty"`

	// Issuer Information about the issuer of the certificate.
	Issuer Issuer `json:"issuer"`

	// NotAfter The end date of the certificate's validity period.
	NotAfter time.Time `json:"notAfter"`

	// NotBefore The start date of the certificate's validity period.
	NotBefore time.Time `json:"notBefore"`

	// Serial The serial number of the certificate.
	Serial string `json:"serial"`

	// Subject The subject of the certificate.
	Subject string `json:"subject"`
}

// X509ManagedCert defines model for X509ManagedCert.
type X509ManagedCert struct {
	// AltNames A list of alternative names (SANs) for the certificate
	AltNames *[]string `json:"altNames,omitempty"`

	// CommonName The common name (CN) for the certificate
	CommonName *string `json:"commonName,omitempty"`

	// Id Unique identifier for the certificate configuration
	Id *string `json:"id,omitempty"`

	// IpSans A list of IP SANs for the certificate
	IpSans *[]string `json:"ipSans,omitempty"`

	// Role The role associated with the certificate
	Role *string `json:"role,omitempty"`

	// Ttl The time-to-live (TTL) duration for the certificate
	Ttl *string `json:"ttl,omitempty"`
}

// BadRequest A generic HTTP problem
type BadRequest = Problem

// Forbidden A generic HTTP problem
type Forbidden = Problem

// InternalServerError A generic HTTP problem
type InternalServerError = Problem

// NotFound A generic HTTP problem
type NotFound = Problem

// NotImplemented A generic HTTP problem
type NotImplemented = Problem

// Unauthorized A generic HTTP problem
type Unauthorized = Problem

// K0sPostActionParamsAction defines parameters for K0sPostAction.
type K0sPostActionParamsAction string

// LibvirtPostDomainActionParamsAction defines parameters for LibvirtPostDomainAction.
type LibvirtPostDomainActionParamsAction string

// PkiSshSignaturesGetParams defines parameters for PkiSshSignaturesGet.
type PkiSshSignaturesGetParams struct {
	// Type Specifies whether to return cert of type user or host. See Vault documentation.
	Type PkiSshSignaturesGetParamsType `form:"type" json:"type"`
}

// PkiSshSignaturesGetParamsType defines parameters for PkiSshSignaturesGet.
type PkiSshSignaturesGetParamsType string

// PkiSshSignaturesPostParams defines parameters for PkiSshSignaturesPost.
type PkiSshSignaturesPostParams struct {
	// Type Specifies whether the cert you want to sign is of type user or host. See Vault documentation.
	Type PkiSshSignaturesPostParamsType `form:"type" json:"type"`

	// ForceRenewal Do not check the lifetime of the existing certificate against the threshold and force a new signature of the host key
	ForceRenewal *bool `form:"force-renewal,omitempty" json:"force-renewal,omitempty"`
}

// PkiSshSignaturesPostParamsType defines parameters for PkiSshSignaturesPost.
type PkiSshSignaturesPostParamsType string

// SecretsReplicationPostParams defines parameters for SecretsReplicationPost.
type SecretsReplicationPostParams struct {
	// SecretPath The KV2 path of the secret that you want to trigger the sync for
	SecretPath string `form:"secret-path" json:"secret-path"`
}

// ServicesUnitStatusPutParamsAction defines parameters for ServicesUnitStatusPut.
type ServicesUnitStatusPutParamsAction string

// SystemPowerConditionalRebootPostStatusParamsAction defines parameters for SystemPowerConditionalRebootPostStatus.
type SystemPowerConditionalRebootPostStatusParamsAction string

// SystemPowerPostActionParamsAction defines parameters for SystemPowerPostAction.
type SystemPowerPostActionParamsAction string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start k0s
	// (POST /v1/k0s/actions/{action})
	K0sPostAction(w http.ResponseWriter, r *http.Request, action K0sPostActionParamsAction)
	// Set status of libvirt domain
	// (POST /v1/libvirt/domains/{domain}/{action})
	LibvirtPostDomainAction(w http.ResponseWriter, r *http.Request, domain string, action LibvirtPostDomainActionParamsAction)
	// Lists installed packages
	// (GET /v1/packages/installed)
	PackagesInstalledGet(w http.ResponseWriter, r *http.Request)
	// Checks for updates
	// (GET /v1/packages/updates)
	PackagesUpdatesGet(w http.ResponseWriter, r *http.Request)
	// Upgrades all packages
	// (POST /v1/packages/upgrade-requests)
	PackagesUpgradeRequestsPost(w http.ResponseWriter, r *http.Request)
	// Get info about a signed host public key certificate
	// (GET /v1/pki/ssh/signatures/{id})
	PkiSshSignaturesGet(w http.ResponseWriter, r *http.Request, id string, params PkiSshSignaturesGetParams)
	// Sign a SSH public key
	// (POST /v1/pki/ssh/signatures/{id})
	PkiSshSignaturesPost(w http.ResponseWriter, r *http.Request, id string, params PkiSshSignaturesPostParams)
	// Returns info of configured managed x509 certificate
	// (GET /v1/pki/x509/certs/{id})
	PkiX509GetCert(w http.ResponseWriter, r *http.Request, id string)
	// Returns info of configured managed x509 certificate
	// (GET /v1/pki/x509/configs/{id})
	PkiX509GetConfig(w http.ResponseWriter, r *http.Request, id string)
	// Prints current configuration
	// (GET /v1/secrets/replication)
	SecretsReplicationGet(w http.ResponseWriter, r *http.Request)
	// Replicate a secret from Vault
	// (POST /v1/secrets/replication)
	SecretsReplicationPost(w http.ResponseWriter, r *http.Request, params SecretsReplicationPostParams)
	// Get logs of a system service unit
	// (GET /v1/services/{unit}/logs)
	ServicesUnitLogsGet(w http.ResponseWriter, r *http.Request, unit string)
	// Interact with a system service
	// (PUT /v1/services/{unit}/status/{action})
	ServicesUnitStatusPut(w http.ResponseWriter, r *http.Request, unit string, action ServicesUnitStatusPutParamsAction)
	// Get reboot status
	// (GET /v1/system/power-state/conditional-reboot/status)
	SystemPowerConditionalRebootGetStatus(w http.ResponseWriter, r *http.Request)
	// Unpause reboot status
	// (PUT /v1/system/power-state/conditional-reboot/{action})
	SystemPowerConditionalRebootPostStatus(w http.ResponseWriter, r *http.Request, action SystemPowerConditionalRebootPostStatusParamsAction)
	// Directly interact with the power status of the system
	// (POST /v1/system/power-state/{action})
	SystemPowerPostAction(w http.ResponseWriter, r *http.Request, action SystemPowerPostActionParamsAction)
	// Send a WOL packet
	// (POST /v1/wol-message/{alias})
	WolPostMessage(w http.ResponseWriter, r *http.Request, alias string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// K0sPostAction operation middleware
func (siw *ServerInterfaceWrapper) K0sPostAction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "action" -------------
	var action K0sPostActionParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.K0sPostAction(w, r, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LibvirtPostDomainAction operation middleware
func (siw *ServerInterfaceWrapper) LibvirtPostDomainAction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "domain" -------------
	var domain string

	err = runtime.BindStyledParameterWithOptions("simple", "domain", r.PathValue("domain"), &domain, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action LibvirtPostDomainActionParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LibvirtPostDomainAction(w, r, domain, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PackagesInstalledGet operation middleware
func (siw *ServerInterfaceWrapper) PackagesInstalledGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PackagesInstalledGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PackagesUpdatesGet operation middleware
func (siw *ServerInterfaceWrapper) PackagesUpdatesGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PackagesUpdatesGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PackagesUpgradeRequestsPost operation middleware
func (siw *ServerInterfaceWrapper) PackagesUpgradeRequestsPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PackagesUpgradeRequestsPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PkiSshSignaturesGet operation middleware
func (siw *ServerInterfaceWrapper) PkiSshSignaturesGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PkiSshSignaturesGetParams

	// ------------- Required query parameter "type" -------------

	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PkiSshSignaturesGet(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PkiSshSignaturesPost operation middleware
func (siw *ServerInterfaceWrapper) PkiSshSignaturesPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PkiSshSignaturesPostParams

	// ------------- Required query parameter "type" -------------

	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "force-renewal" -------------

	err = runtime.BindQueryParameter("form", true, false, "force-renewal", r.URL.Query(), &params.ForceRenewal)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force-renewal", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PkiSshSignaturesPost(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PkiX509GetCert operation middleware
func (siw *ServerInterfaceWrapper) PkiX509GetCert(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PkiX509GetCert(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PkiX509GetConfig operation middleware
func (siw *ServerInterfaceWrapper) PkiX509GetConfig(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PkiX509GetConfig(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SecretsReplicationGet operation middleware
func (siw *ServerInterfaceWrapper) SecretsReplicationGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SecretsReplicationGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SecretsReplicationPost operation middleware
func (siw *ServerInterfaceWrapper) SecretsReplicationPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SecretsReplicationPostParams

	// ------------- Required query parameter "secret-path" -------------

	if paramValue := r.URL.Query().Get("secret-path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "secret-path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "secret-path", r.URL.Query(), &params.SecretPath)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret-path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SecretsReplicationPost(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ServicesUnitLogsGet operation middleware
func (siw *ServerInterfaceWrapper) ServicesUnitLogsGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "unit" -------------
	var unit string

	err = runtime.BindStyledParameterWithOptions("simple", "unit", r.PathValue("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServicesUnitLogsGet(w, r, unit)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ServicesUnitStatusPut operation middleware
func (siw *ServerInterfaceWrapper) ServicesUnitStatusPut(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "unit" -------------
	var unit string

	err = runtime.BindStyledParameterWithOptions("simple", "unit", r.PathValue("unit"), &unit, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unit", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action ServicesUnitStatusPutParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServicesUnitStatusPut(w, r, unit, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SystemPowerConditionalRebootGetStatus operation middleware
func (siw *ServerInterfaceWrapper) SystemPowerConditionalRebootGetStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPowerConditionalRebootGetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SystemPowerConditionalRebootPostStatus operation middleware
func (siw *ServerInterfaceWrapper) SystemPowerConditionalRebootPostStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "action" -------------
	var action SystemPowerConditionalRebootPostStatusParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPowerConditionalRebootPostStatus(w, r, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SystemPowerPostAction operation middleware
func (siw *ServerInterfaceWrapper) SystemPowerPostAction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "action" -------------
	var action SystemPowerPostActionParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPowerPostAction(w, r, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// WolPostMessage operation middleware
func (siw *ServerInterfaceWrapper) WolPostMessage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "alias" -------------
	var alias string

	err = runtime.BindStyledParameterWithOptions("simple", "alias", r.PathValue("alias"), &alias, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "alias", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WolPostMessage(w, r, alias)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/k0s/actions/{action}", wrapper.K0sPostAction)
	m.HandleFunc("POST "+options.BaseURL+"/v1/libvirt/domains/{domain}/{action}", wrapper.LibvirtPostDomainAction)
	m.HandleFunc("GET "+options.BaseURL+"/v1/packages/installed", wrapper.PackagesInstalledGet)
	m.HandleFunc("GET "+options.BaseURL+"/v1/packages/updates", wrapper.PackagesUpdatesGet)
	m.HandleFunc("POST "+options.BaseURL+"/v1/packages/upgrade-requests", wrapper.PackagesUpgradeRequestsPost)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pki/ssh/signatures/{id}", wrapper.PkiSshSignaturesGet)
	m.HandleFunc("POST "+options.BaseURL+"/v1/pki/ssh/signatures/{id}", wrapper.PkiSshSignaturesPost)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pki/x509/certs/{id}", wrapper.PkiX509GetCert)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pki/x509/configs/{id}", wrapper.PkiX509GetConfig)
	m.HandleFunc("GET "+options.BaseURL+"/v1/secrets/replication", wrapper.SecretsReplicationGet)
	m.HandleFunc("POST "+options.BaseURL+"/v1/secrets/replication", wrapper.SecretsReplicationPost)
	m.HandleFunc("GET "+options.BaseURL+"/v1/services/{unit}/logs", wrapper.ServicesUnitLogsGet)
	m.HandleFunc("PUT "+options.BaseURL+"/v1/services/{unit}/status/{action}", wrapper.ServicesUnitStatusPut)
	m.HandleFunc("GET "+options.BaseURL+"/v1/system/power-state/conditional-reboot/status", wrapper.SystemPowerConditionalRebootGetStatus)
	m.HandleFunc("PUT "+options.BaseURL+"/v1/system/power-state/conditional-reboot/{action}", wrapper.SystemPowerConditionalRebootPostStatus)
	m.HandleFunc("POST "+options.BaseURL+"/v1/system/power-state/{action}", wrapper.SystemPowerPostAction)
	m.HandleFunc("POST "+options.BaseURL+"/v1/wol-message/{alias}", wrapper.WolPostMessage)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc/3PbtpL/VzC8m3ntPEmUE7tN9NOlaZN66rqeKGnfXa/jgciViCcKYAHQti7j//1m",
	"FyAJfpGsxGm+NJnJZGQRWCx2P7vYXSz1OkrUplASpDXR7HWkwRRKGqA/vuPpC/izBGPxr0RJC5I+8qLI",
	"RcKtUDIutFrksPnnv42S+Axu+KbIAT+mYLnIo1n0MgOmHSUmDBPyiuciZUqzjTBGyBU9FRpSVnDNN2BB",
	"m0k0iozltjTR7Hg6HUVWWKSLbLGKr1FktwV+mVlbmFkc++UnidrEoLXSJl7wdOxXj25HkUky2HDk7z81",
	"LKNZ9B9xI4PYPTXxhdtWdHs7GtzuzSb/W+72dhSlYBItCtxuZ/3bUfRM6YVIU5D3hMSTJAFjUD7LiiJ+",
	"YjYDVmh1JVJIWaIhBWkFzzvyedjIp2HoEOnUi70XJHyKm+wB4FlI7VRa0JLnc9BXoH/A9e4LBMlKCTcF",
	"JBZSRjtgKklKrSEN5XESGkXFBnN8MMfIIbIRfubY0Mwxff1+wPCJbrQHiGGebkfRubLPVCnTd3daQMo0",
	"GFXqBNg1N0wqy5a4RNtSjhuBnSvLHBOHCEkqOyZ67/tg+Kg31tN4s7bT8ikutwFp4f66RudYygRnoKNE",
	"QYDki7xrFEdtUYQsHCoQEcx5P/r+dDY3qPPTNs1Xkpc2U1r83731/t+qZKkigWT8CuhElICnJddbVoCm",
	"UEnJzpEYyKnFzCFCKsMJ70P9n+AeeyhocXBbU6T04Hu5vODJmq/gVC6V23r7nFgqxheqtIwzjHtzYIWb",
	"EI1CiUm+wX3JlZA30SjSUKhoFm24wHDnCrRx9I4mR48mU9xWoVUB2gqXprjp3dXP+QaYWrpYq79qvZoX",
	"qrFayBUSd8t3yb2AQhlhld6ypVYbdp2JJAuJkxsX0lie56StZim/k95K9da6i/3qHuxj3wujR/W2/kYt",
	"/g0JxeynxpSghxWkN4RnrydcTdDoau0E5bxE1APCtC35RG02Sp4Pyh8PO/ecyUAVjvpkSBwGtOD5eblZ",
	"DDGL9NwIJmnInRRJly7Rima/t8mPQt7/GJDZmVqZARTwa5arFUu55W0M5zT+9+gZLNj0IXtwNDt+NDt5",
	"wHKV8DxTxk7oU6oQDGwNWkI+Y/MfzoQsb2bswfT4EeNXli9Yxk3GTK6sGbGj6fHRwyOmyxzIS/yV1P/o",
	"GVbuZSAsbOhDT2UbfnPqHh5NKWx1A7jWfBuNopvxSo3xu7FZi2KsSIw8HxeKotNoZnUJg5D1jsWcVgb1",
	"whcm+jo5E8YiFnieOzxUUyq7MQzxzczWWNi0tVaNiGa/v7Eb6surobaLxz5v0agR7z4f3XG2tx1ZkxD9",
	"qbHI+SLn0R6pvipSbsHslukLsKWWhl1nYDPQXnasdPMY18D4FRe4UMeX0xD8+vJesh1Ffq3LZh2Hlq7Q",
	"hxbcJf4aEDbjliVcsgX4TaXvShGDnPc9b0ou1TBBTgzlqaGR75Bscff1YgulcuBy2N9frMXcZE+VXIpV",
	"f+0fVZ7iSTXk+wNvz7hM/SnHXQCLB5zlaypCBBrHOS8dC9og7PCLS+FDgoDi5VIQPuOC2yy2Kg7PloJM",
	"MxxtQ5oF6ASkxVNw9u3J5GQUFeUiF8nlGrY9us0jT5YKcJd8ST4nejB98HA8fTSeHr2cTmf073/qQQtY",
	"Kg1u1HFv1G2LxWd+3UxtIC4N6HhiTBaL9FIbPkm0pQNTyEQUPKfTgacbQrwUm5TjueNY/Qm2+2kV5QKt",
	"RrlwYjumT6PIWowzjx9l/aCo0cqA225paB/Y5yabi5UE/bTZdQX7niCGTmxUDbOKXWthXQRskF5KSGNW",
	"tWKavYLsbSKUbBCADwi5tutOlEVl2YZMXZoLWGzxVxHusdL1AB2t7hOMBp7SovP5j8zNY2twQeYhwnHI",
	"6AexKr8jJr7iZW6ZB1IQqzbg6u3S5sN7ScFQNfvly7OKOoqQ21K3iSNSD4pYq4ykt9wTtgIJWiTsx5cv",
	"L5jPwtoOaWcCBlKVq4wKrsJiOEXHsUxIvDxJVCltfPTg4fFJvDErE/NFsqsqfyfpPbkaMm1iVdqxWo7d",
	"jL79VpvoCyArN1yOETd4QjC4KXIunSM3BSRokggsmwlT1Rdl0qRCfYnhZjRzAy1b8BxFwoRhD6cjtqCT",
	"AU9LZaxhJ9PB0L0RZJ/fVy9OmYYlODaIlqCC91LQSQwN24exu1tV/ZTC624ItQQgN4AlKm0h9TgIZjFU",
	"XQEVOL32+3s0mdJ21FWNKTcbTPXbe2FEtyP/g8DUdThvI+udTByK1CH79UUQH+Q1OsMvTMHJwEotZwLs",
	"cqaXyezbR9NvaeYcEg32BdSFldNhXx0G+QkFNiV6HLOVCXPuve0CMD/DuDMFYy9LLRA2dlPE6WJCZalR",
	"5MIfFxH4rwwxc4lhhNtGGqeLoUDfkR/MUEOGDoonnQTmW5mAxv9RAL0z5T6p1OACPeafeqE6R4InYV2z",
	"cWJxW9P1TWTL4d5fyH3/V9HscopPhHd4SAWTFO1iCzpMK3YzVeYpBvgUe8hesNHmtA3qQ+Xd2mGX0bDs",
	"0QwLebjn2i1Rdlcn0VSnsRNJFW5gZE/apGMCXBWBIpJ+jlxr6G3ZHIakvhIJnKmV+X7QlPAJFVkqJLoJ",
	"Q0b+9yi97HQx+1wH1ahuRxFU17CyzINU+aBIa2eE39PJcwy8eD6QOXIKXoN8oJ8g/q1SwH6m1d7e69DN",
	"7N7pYFrW3npI6cX8yWAaFIglGP748eRx5Z2iWbTMFQ/ObldBbVKVQIaDzPfEuaN425pO4dk33z4K+RDS",
	"fnMcDcVWLQWFTOzQVU0y5RbGVmwGc5a2Rjtkj9+S7JAd/etk+hhNaPdVSMdmJMMp++vrsOEif5KmGowZ",
	"qms9YbmPi2gk49VQxo1RieAWUnYtbDZUyq+jk3rLROSQ/FbUFwr73JO/drgdRVLZJ0u7q6oPMkVfDwNX",
	"Dv8wjDQoLF2YCUX3poepXir7Xa33gUjNcm3/inUbSzjwAqOjlz7B0qFsmKJ7eBitzo2IV2OzQs18KL1A",
	"fX/sAP7PXPIVpIh/qoO3QMxze455wD748pxaSqy4ArotMuyr+ZNz83VdkmkfLrsvJLpIfZMbqq+enu9a",
	"sJ/wpn16r6T4s4Qm4dJDxOrshZzBIOlizuVeaZ1eMJTOvYUzXCSiLhWVw10+5I1KRGgsY6vGOWr4q5cv",
	"z75maZhs3Em773Nvqe7gq8xKWu5MxDmxWXTyzTffTh9Oj/9pFKbDJskkiBT0f5UGtJlIpaHIt5OVsFm5",
	"wGzX56u4Js1g9ZRoFJU6D3LkZlLcoR6bZMxXIMk0Ovq7OMWAm2Jjnlgn03r4KMpFAv4yxvNx/sv5D/Xa",
	"UkkIahBRMDO8P5m6G3JVgOQFZmQPJ9PJQzxZuM0IFvHVUbyemthV9U382n24JctVZsDPzMlVoorWU1PF",
	"4uhe0Mxd1p5Gs+inqblQxj5JPLKb5tYqFQ+l4e4UrEL/io61hkGwRisRMVYVVLPzyU2jL16t2Dg3F/82",
	"7Q8gyw1dAjsi5PwDd1aj7I9RuwX6wXQ6lCtvNphDWeVPEWTZXf9fqTWkzJTU+Lks85wM7dhRGTos69Xi",
	"oNuapjy8e0qrNfPkkEWG+jdp7tHdczuNX9QN4ipcNUbWU4Omy11Chn9RaoOQy8XiSmgbu0TJxK/dh9sD",
	"8HfaMhnrDm9bGjo5mCfMfAamSymFXDEEVwZsw5NMSFceQAvUpTRMyQn7TtmsmkPuHzXqb7q4xqPaMm5c",
	"heGKa4F51eR/ZQ/1Z255RP73RO0w/KNTDAsEnpOtKtk1l5Srm6y0qbpuXbdVn8Zu/LA91M9220PPux5u",
	"n215t5jTsFDK3ttIazKBBO5nsU4ztUQDA31v5nk8PT7IxOo+yw9sz2ADK+vpvDJx/6Ax8+qKPW5aoWav",
	"oxXYHTVdnudDHRtUukYzbJ5dCe5sn2pU/zB149WGok/dP5B6TSTPwUbDcNnRyli1MB7YR7ezaWWgs64J",
	"5+pNt/f6/fmz+MXFz5Uj86W5z+M0QWiY4W6ZCnn1V33o+TaKncB7mkGyptYLLreN+JsODLq98TrYiSrf",
	"RPOeMNVt2RlAVLdpZ7Bbh9z4bsR9JvjyCEBZVGA5EFkrzVOoXrAyu2OWV26kIQdXy7sOYFJY0v1714ex",
	"U1s1imvA5BRcnFkacDe6IFOqr7ueNg2rMueaLbgRZrIHqsSMVxhF6dEhx6afR7HtBzgyPyxGBjW4HyZr",
	"ERuTxXXzg4lfi/R2px96AVYLuALXjbWnDUt7y6br146KqddrXq/o3NGdoadIq8BzPv+RZcrY1qJhGKo9",
	"l63C/1LpbtsIEhn7npmB+E+k9wtI565JABr/5ngrtXTNRLifbQFoKpopTZuasDkA+5VMLVVJiYqmDUxa",
	"3OOUius/S9Dbhm1/T3530Opp4KpvEKa+mzMi7PcbfGGrha5a42vYtoouX0LhQUfwHGxooLzqDyMZBi1b",
	"nfpV5SbWwrVWD5dWxEoaf4EWkKLeSy1s1SBTmTdintNN7YShGfOi0KrQAm02mC4MK0SyhtS9q0AupXW/",
	"j/RxEDfGn/2U59Zuw1FvU1Qy31ZbF0vm5eDYShX4t5tuXFCvgadbtEKxbC0PKbOZBpOpvPZAGjCpwJw9",
	"F0uwYkPNR3CTAKSQDuXcXafnD7R36fVwb10Phyb+fj2cPwt6nJE+Pmp/N+qn4ASQBCMvX0fwyvYqIegg",
	"Clqn34pjjEoDGuAgfJdKJ8A4k3AdANHTqtzbjk3S3LEGCdd02dFTUtNefVhBMOTYY5+2YypLM1bkubtT",
	"GjGpOlzTG6CEdvRYD5zH6rRutiYkGriFdMRAEFAWkHAMEUPRpSJtTHJEa8BNgUp1fywgV9dtTQSm2dAk",
	"YV16YblQ0PWSIDImXw6NHfUTtNKuX+8dC0HgeHMyfUxNAncEjU+SBArrzoXGnwX+1aUSKbvpXC/X1cza",
	"TXZiS+OpTIb87b9Opo+fg33qvN8beNqd7LxNjEku9v6u968MxlqNAHcHYz3xfDGoYYOqqhsUianlIYi/",
	"29yIxsdtcC6q/2Jyd5hc2ILwxeo+RqtzTai4cq3nfZURWpYszb+Y0M5g2p2tAU1Wb7JvVq4V2gTt5n9x",
	"9XZHe/sAQF8euFNDfdyfSQnuQguJXnJILgHMPLL2pNmVBgBz7UJDCkuBeawXKmXJLmva0RLtEmI/3PGB",
	"YX1FZ7ENdeS70kWSuUTW/+QPN4zykCDNHsht+xg9NLv96dcHbKjrO+PtBNJqsVr57JLawLte37V8c8sX",
	"3MCOFMoRH/sz4d7nQCcTDvonHOIrVX0mwK/xSr3vHYwOIr92stQ4Y+LXpRT2Nq5e4d9bf2Y4quq09296",
	"S2Ed5vET25TGskXwo2VC+l+msNmQm3VMvJLCnqnVoTXpsB3Cs+G345igoMX9rF7FcLtByGTppOkcGohZ",
	"kMxHE7V0X4IYOBToNYgqUHtHbUUHQPNV51dkPosKL0GKGooGsNcyOQfu3Tbn2ibafU3lnrYmfy3YXXjC",
	"0H6G2pKqeu1+y5sTGxflu7K9BTAN1IbT+Xmbv8Du3qAdaVhbYdsg1x9jS5LfUcK1FpAyzExC+6ZK78DW",
	"vuQpgxbcbhHsmlJovq6NpjFe+jsu1DXoMVouxImSqfDvsjm9x817xHvSlVa24ib6FqoBQ6VlL3DVp81y",
	"L2jSc/C2e9/MpN2H3+whiPR4acKfFtvfbd3ddLDDd31KfVrh2nPoKPzegLvz8JiD9RFYacJ+WF+bqujV",
	"bNWGcDgOMe+ogfiWzdz9rQ32dtMu7u2kKyqldJ/e1jW3ke2ppZ9L24vb7n3wfMAbBYBRjawCm1bS7V03",
	"pa3+egtdiwlbopnSFYPtJm9hqMtbmKAPvH9Vzutf5AzDqb1t3oGhvIuXHDzH76d7+m3t4Gcv1g/ZNv1h",
	"jeF7oSGx+bbz1g45XoRCx/HWr8/vMpZrlY83YAxfoZXkgps9RvJU86VlnP32yxn1n1W1nGu+BsPKgvEa",
	"+CX9rPxvfA1jJcdnT8495nGFfvK+2O5IH35TOYL7Z8fhIXlDUA92i9VXEN4iFTNk661dtH+JQSqLkF3v",
	"QD6SffclpgrbKMyycFfrOfJqP0wA88m9HtBRagD6a5Uj4t2rsFfD2Dlzrp6et16vm8Vx/csKs8ePHz+m",
	"HwP0pHsI5CvyqOspBqA5vapYNciaBkLrqYn6KWU1uXq3YQ+B6i2H3UTqDt89VOqG0d1kLn463UthLfZM",
	"bt0Q7CNTVQ33kXIp514ivg6yh4o7yfcRqV5q2EUicGnsq99+Oft6HzUE3u0ft/8fAAD//50jMC/UZAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
